# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Macrometa Inc."]
description = "Macrometa jsc8 driver with Fastly Compute@Edge."
language = "javascript"
manifest_version = 2
name = "tutorial-fastly-compute-jsc8"
service_id = ""


[local_server]
  [local_server.backends]
    [local_server.backends.gdn_url]
      url = "https://api-gdn.paas.macrometa.io"
